name: forest_guard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  camera: ^0.10.5+8
  exif: ^3.3.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.6
  image: ^4.1.3
  google_mlkit_text_recognition: ^0.11.0
  google_nav_bar: ^5.0.6
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  tflite_flutter: ^0.10.4
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
     - assets/models/log_model/best_float32.tflite
     - assets/models/log_model/labelmap.txt
     - assets/models/license_plate/best_float32.tflite
     - assets/models/license_plate/labelmap.txt
     - assets/images/truck.svg

  uses-material-design: true
